export default {
  root: {
    maxWidth: "300px",
    backgroundColor: "white",
    borderRadius: "5px",
    padding: "0.5rem",
    position: "relative",
    cursor: "pointer",
    fontSize: 0,
    "&:hover svg": {
      opacity: 1,
    },
  },
  colors: {
    backgroundColor: "white",
    height: "150px",
    width: "100%",
    borderRadius: "5px",
    overflow: "hidden",
  },
  title: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    color: "black",
    fontSize: "13px",
  },
  minicolor: {
    height: "20%",
    width: "25%",
    margin: "0 auto",
    display: "inline-block",
    position: "relative",
  },
  delete: {},
  deleteIcon: {
    color: "white",
    backgroundColor: "red",
    width: "25px",
    height: "25px",
    position: "absolute",
    top: "0",
    right: "0",
    zIndex: "10",
    padding: "1px",
    opacity: 0,
  },
};
