export default {
  palette: { height: "100vh", display: "flex", flexDirection: "column" },
  paletteColors: { height: "90%" },
  goBack: {
    width: "20%",
    height: (props) => (props.showingFullpalette ? "25%" : "50%"),
    display: "inline-block",
    margin: "0 auto",
    position: "relative",
    cursor: "pointer",
    marginBottom: "-3.5px",
    opacity: "1",
    backgroundColor: "black",
    "& a": {
      color: "white",
      width: "100px",
      height: "30px",
      position: "absolute",
      top: "50%",
      left: "50%",
      backgroundColor: "rgba(0, 0, 0, 0.164)",
      marginLeft: "-50px",
      marginTop: "-15px",
      textAlign: "center",
      fontSize: "12px",
      textTransform: "uppercase",
      outline: "none",
      border: "none",
      borderRadius: "20px",
      cursor: "pointer",
    },
  },
};
